Sprint1/step1
veron1213/react-burger pull request #1
Opened 2024-07-22 18:40 UTC by veron1213

A layout for intermediate testing has been created.

2024-07-22 21:08 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;

### **Но есть несколько замечаний, которые нужно исправить:**

- В компоненте App-header требуется поправить семантику, переделать div в ссылки.

- В директории `components` должен быть компонент App. Компонент `App`, он также должен быть в папке (как и другие компоненты). Как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  ```

  Проверьте во всём проекте.

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

- Старайтесь разделять компоненты по папкам и файлам, а не писать всё в одном файле, это нарушает структуру и читаемость кода.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2024-07-22 21:08 UTC, ArslanMustafin commented on src/App.jsx
> +      <main style={{ display: 'flex', justifyContent: 'center', gap: '40px'}}>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2024-07-22 21:08 UTC, ArslanMustafin commented on src/components/burger-constructor/BurgerConstructor.jsx
> +      <div style={{display: "flex", flexDirection: 'column', gap: '8px', width:'612px', height:'450px', overflow:'hidden', overflowY: 'scroll', scrollbarWidth: 'thin'  }} className='pb-2'>
**Надо исправить:**

Здесь и далее.

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2024-07-22 21:08 UTC, ArslanMustafin commented on src/components/burger-constructor/BurgerConstructor.jsx
> +  burgerIngr: PropTypes.node
**Надо исправить:**

Требуется полное описание структуры ингредиента, а не propTypes.any.
А также необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientType.isRequired).isRequired;
```

Во многих компонентах будет дублироваться описание PropTypes ингредиента.
Следует вынести его в отдельный файл (можно создать файл `prop-types.js` в папке `utils`) и переиспользовать описание пропсов ингредиента, а не дублировать;

2024-07-22 21:08 UTC, ArslanMustafin commented on src/components/burger-constructor/BurgerConstructor.jsx
> +const ViewIngredientsConstructor = ({burgerIngr}) => {
**Надо исправить:**

Лучше эту часть кода вынести в отдельный компонент (папку и файл) для улучшения структуры и читаемости.

2024-07-22 21:08 UTC, ArslanMustafin commented on src/components/burger-constructor/BurgerConstructor.jsx
> +}
**Надо исправить:**

Лучше эту часть кода вынести в отдельный компонент (папку и файл) для улучшения структуры и читаемости.

2024-07-22 21:08 UTC, ArslanMustafin commented on src/components/burger-constructor/BurgerConstructor.jsx
> +const IngredientsConstructor = ({burgerIngr}) => {
**Надо исправить:**

Это лучше написать сразу в компоненте BurgerConstructor, не нужно выносить это в отдельный компонент))

2024-07-22 21:08 UTC, ArslanMustafin commented on src/components/burger-ingredients/BurgerIngredients.jsx
> +}
**Надо исправить:**

Лучше эту часть кода вынести в отдельный компонент (папку и файл) для улучшения структуры и читаемости.

2024-07-22 21:08 UTC, ArslanMustafin commented on src/components/burger-ingredients/BurgerIngredients.jsx
> +        </div>
**Можно лучше:**

лучше создать отдельный компонент для отображения ингредиента, и переиспользовать его.

2024-07-22 21:08 UTC, ArslanMustafin commented on src/components/burger-ingredients/BurgerIngredients.jsx
> +const ViewIngredients = ({burgerIngr, name, type}) => {
**Надо исправить:**

Лучше эту часть кода вынести в отдельный компонент (папку и файл) для улучшения структуры и читаемости.

2024-07-22 21:08 UTC, ArslanMustafin commented on src/components/burger-ingredients/BurgerIngredients.jsx
> +}
**Надо исправить:**

https://disk.yandex.com/i/hiYxhvj4EoqZ4Q - у вас возникает ошибка, т.к. вы используете `Ingredients` до инициализации.

2024-07-23 20:35 UTC, veron1213 commented on src/components/burger-ingredients/BurgerIngredients.jsx
> +}
Ingredients.propTypes перемещен

2024-07-23 20:35 UTC, veron1213 commented on src/components/burger-ingredients/BurgerIngredients.jsx
> +const ViewIngredients = ({burgerIngr, name, type}) => {
Вынесено в отдельный компонент

2024-07-23 20:36 UTC, veron1213 commented on src/components/burger-ingredients/BurgerIngredients.jsx
> +        </div>
Вынесено в отдельный компонент

2024-07-23 20:36 UTC, veron1213 commented on src/components/burger-ingredients/BurgerIngredients.jsx
> +}
Вынесено в отдельный компонент

2024-07-23 20:36 UTC, veron1213 commented on src/components/burger-constructor/BurgerConstructor.jsx
> +const IngredientsConstructor = ({burgerIngr}) => {
Перемещено в компонент

2024-07-23 20:36 UTC, veron1213 commented on src/components/burger-constructor/BurgerConstructor.jsx
> +}
Вынесено в отдельный компонент

2024-07-23 20:36 UTC, veron1213 commented on src/components/burger-constructor/BurgerConstructor.jsx
> +const ViewIngredientsConstructor = ({burgerIngr}) => {
Вынесено в отдельный компонент

2024-07-23 20:37 UTC, veron1213 commented on src/components/burger-constructor/BurgerConstructor.jsx
> +  burgerIngr: PropTypes.node
Создан отдельный файл и переиспользован)

2024-07-23 20:37 UTC, veron1213 commented on src/components/burger-constructor/BurgerConstructor.jsx
> +      <div style={{display: "flex", flexDirection: 'column', gap: '8px', width:'612px', height:'450px', overflow:'hidden', overflowY: 'scroll', scrollbarWidth: 'thin'  }} className='pb-2'>
Стили были вынесены в отдельные файлы

2024-07-23 20:37 UTC, veron1213 commented on src/App.jsx
> +      <main style={{ display: 'flex', justifyContent: 'center', gap: '40px'}}>
Стили были вынесены в отдельные файлы

2024-07-24 15:30 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличая работа. 🔥

### **Вы молодец! Приступайте к выполнению следующего этапа, не пугайтесь, работа не принята, чтобы была возможность отправить на проверку следующий этап.**

- Все замечания были исправлены;

### **Сделает код лучше:**

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь <https://learn.javascript.ru/coding-style>. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (<https://prettier.io/>)

- Используйте функциональные компоненты, а не классовые. Сейчас при разработке на React стремятся отдавать предпочтение функциональным компонентам, эти компоненты в проекте можно легко переписать как функциональные с использованием хуков.

2024-07-24 15:30 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +}
**Надо исправить:**

Тут лучше не выносить эту часть кода в отдельный компонент.

Это можно сразу написать в `BurgerIngredients`.

```js
class BurgerIngredients extends React.Component {
  render() {
    return (
      <div>
        <p className='text text_type_main-large pt-10'>Соберите бургер</p>
        <Tabs />
        <div>
          <p className='text text_type_main-large pt-10'>Соберите бургер</p>
          <Tabs />
          <div className='ingredients'>
            <ViewIngredients burgerIngr={burgerIngr} name='Булки' type='bun' />
            <ViewIngredients burgerIngr={burgerIngr} name='Соусы' type='sauce' />
            <ViewIngredients burgerIngr={burgerIngr} name='Начинки' type='main' />
          </div>
        </div>
      </div>
    );
  }
}
```

**Можно лучше:**

Лучше в компоненте делать filter по массиву, а потом отображать полученный массив.

Например:

```js
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);
```

А не располагать фильтрацию в `ViewIngredients`

2024-08-04 09:56 UTC, merged